

set(libMaths_SOURCES
	source/Algorithm/CORDIC.h
source/Algorithm/CORDIC_0.cpp
source/Algorithm/CORDIC_9.cpp
source/Algorithm/CORDIC_r.cpp
source/Core/Angle.cpp
source/Core/Angle.h
source/Core/AngleDefine.h
source/Core/CMath.cpp
source/Core/CMath.h
source/Interpolation.cpp
source/Interpolation.h
source/Matrix/Matrix.h
source/Matrix/Matrix2.cpp
source/Matrix/Matrix2.h
source/Matrix/Matrix3.cpp
source/Matrix/Matrix3.h
source/Matrix/Matrix4.cpp
source/Matrix/Matrix4.h
source/pch.h
source/Quaternion/Quaternion.cpp
source/Quaternion/Quaternion.h
source/Random.cpp
source/Random.h
source/Test.cpp
source/Test.h
source/Vector/TVector2.h
source/Vector/Vector.h
source/Vector/Vector2.cpp
source/Vector/Vector2.h
source/Vector/Vector3.cpp
source/Vector/Vector3.h
source/Vector/Vector4.cpp
source/Vector/Vector4.h
	)
